/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muestreo;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import org.apache.commons.math3.distribution.NormalDistribution;
import org.apache.commons.math3.distribution.TDistribution;

/**
 *
 * @author JUAN CAMILO
 */
public class dif_prop extends javax.swing.JFrame {

    /**
     * Creates new form mediaC1
     */
    public dif_prop() {

        initComponents();
        superior.setEditable(false);
        inferior.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pm1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        superior = new javax.swing.JTextField();
        inferior = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pm2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Interpretacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intervalos  de confianza para la proporcion:\n");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Intervalos  de confianza para la diferencia de proporciones:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese los valores de las proporciones muestrales de forma decimal:");

        pm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pm1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ingrese el tamaño de la muestra:");

        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n1KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ingrese el nivel de confianza porcentual:");

        nc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ncKeyTyped(evt);
            }
        });

        jLabel7.setText("Intervalo de confianza:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("≤ P1-P2≤");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("%");

        jButton2.setText("Ingresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("(p1) ̂ =");

        pm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pm2KeyTyped(evt);
            }
        });

        jLabel4.setText("(p2) ̂ =");

        jLabel10.setText("n1 =");

        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n2KeyTyped(evt);
            }
        });

        jLabel11.setText("n2 =");

        Interpretacion.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(inferior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(superior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17)
                                .addComponent(pm1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(pm2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(Interpretacion, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Interpretacion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        pm1.setText(null);
        pm2.setText(null);
        n1.setText(null);
        n2.setText(null);
        nc.setText(null);
        superior.setText(null);
        inferior.setText(null);
        Interpretacion.setText(null);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        try {
            double proporcion1;
            double proporcion2;
            double tamaño1;
            double tamaño2;
            double nivelc;

            if ((pm1.getText().length() == 0) || (pm2.getText().length() == 0) || (n1.getText().length() == 0) || (n2.getText().length() == 0)) {
                //emite señal de error
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Ingrese ambos valores de las proporciones y los tamaños de las muestras para poder hallar el intervalo de confianza", "Error de Campo vacio", JOptionPane.ERROR_MESSAGE);

            } else if ((Double.parseDouble(pm1.getText()) < 0) || (Double.parseDouble(pm1.getText()) > 1) || (Double.parseDouble(pm2.getText()) < 0) || (Double.parseDouble(pm2.getText()) > 1)) {
                //emite señal de error
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "No existen proporciones negativas ni mayores a 1", "Proporcion muestral no valida", JOptionPane.ERROR_MESSAGE);

            } else if ((Double.parseDouble(n1.getText()) < 1)) {
                //emite señal de error
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "No se pueden tener una muetra de tamaño 0 o menos", "tamaño de la muestra no valido", JOptionPane.ERROR_MESSAGE);

            } else {

                //DecimalFormat df = new DecimalFormat("0.00000");
                proporcion1 = Double.parseDouble(pm1.getText());
                proporcion2 = Double.parseDouble(pm2.getText());
                tamaño1 = Double.parseDouble(n1.getText());
                tamaño2 = Double.parseDouble(n2.getText());

                if ((nc.getText().length() == 0)) {
                    JOptionPane.showMessageDialog(this, "se tomara 95% como nivel de confianza", "Nivel de confianza", HEIGHT);
                    nivelc = 95;
                } else {
                    nivelc = Double.parseDouble(nc.getText());
                }

                if ((nivelc > 100) || (nivelc < 0)) {
                    //emite señal de error
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "No es valido tener un nivel de confianza mayor a 100% o menor al 0%", "Nivel de confianza no valido", JOptionPane.ERROR_MESSAGE);

                } else {

                    double porcentaje;
                    porcentaje = nivelc / 100;

                    double alfa2 = (1 - porcentaje) / 2;

                    //////////////////
                    double sup;
                    double inf;
                    double q1 = 1 - proporcion1;
                    double q2 = 1 - proporcion2;

                    NormalDistribution distribution = new NormalDistribution();
                    double outcomeRisk = Math.abs(distribution.inverseCumulativeProbability(alfa2));

                    sup = (proporcion1 - proporcion2) + ((outcomeRisk) * (Math.sqrt(((proporcion1 * q1) / tamaño1) + ((proporcion2 * q2) / tamaño2))));
                    inf = (proporcion1 - proporcion2) - ((outcomeRisk) * (Math.sqrt(((proporcion1 * q1) / tamaño1) + ((proporcion2 * q2) / tamaño2))));

                    superior.setText(String.valueOf(sup));
                    inferior.setText(String.valueOf(inf));

                    if ((sup > 0) && (inf > 0)) {
                        Interpretacion.setText("La proporcion poblacional 1 es mas grande que la media proporcion 2");
                    } else if ((sup < 0) && (inf < 0)) {
                        Interpretacion.setText("La proporcion poblaciona 2 es mas grande que la proporcion poblacional 1");
                    } else {
                        Interpretacion.setText("Se puede decir que la proporcion poblacional 1 es igual a la proporcion poblacional 2");
                    }
                }

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Hay un dato invalido", "Error con algun dato mal ingresado", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void pm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pm1KeyTyped
        //declaro unba variable de tipo char y le digo que me devuelva solo los valores que le diga que me retorne
        char c = evt.getKeyChar();
        //si el char es una letra
        if (Character.isLetter(c)) {
            //emite señal de error
            getToolkit().beep();
            //no deja escribir
            evt.consume();
            //muestra el siguiente mensaje
            JOptionPane.showMessageDialog(this, "Solo ingresa numeros en este campo", "Error de compativilidad", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_pm1KeyTyped

    private void n1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyTyped
        //declaro unba variable de tipo char y le digo que me devuelva solo los valores que le diga que me retorne
        char c = evt.getKeyChar();
        //si el char es una letra
        if (Character.isLetter(c)) {
            //emite señal de error
            getToolkit().beep();
            //no deja escribir
            evt.consume();
            //muestra el siguiente mensaje
            JOptionPane.showMessageDialog(this, "Solo ingresa numeros en este campo", "Error de compativilidad", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_n1KeyTyped

    private void ncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ncKeyTyped
        //declaro unba variable de tipo char y le digo que me devuelva solo los valores que le diga que me retorne
        char c = evt.getKeyChar();
        //si el char es una letra
        if (Character.isLetter(c)) {
            //emite señal de error
            getToolkit().beep();
            //no deja escribir
            evt.consume();
            //muestra el siguiente mensaje
            JOptionPane.showMessageDialog(this, "Solo ingresa numeros en este campo", "Error de compativilidad", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_ncKeyTyped

    private void pm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pm2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pm2KeyTyped

    private void n2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_n2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Interpretacion;
    private javax.swing.JTextField inferior;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField nc;
    private javax.swing.JTextField pm1;
    private javax.swing.JTextField pm2;
    private javax.swing.JTextField superior;
    // End of variables declaration//GEN-END:variables
}
